language: generic

env:
  global:
    - DEV_URL=https://platform-dev.tradelens.com

notifications:
  email:
    recipients:
      - emanaty@eg.ibm.com
    on_success: always
    on_failure: always

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

script:
  - echo "TRAVIS_PULL_REQUEST = $TRAVIS_PULL_REQUEST"
  - echo "TRAVIS_PULL_REQUEST_BRANCH = $TRAVIS_PULL_REQUEST_BRANCH"
  - echo "TRAVIS_BRANCH = $TRAVIS_BRANCH"
  - echo "TRAVIS_JOB_NAME = $TRAVIS_JOB_NAME"
  - echo "TRAVIS_JOB_ID = $TRAVIS_JOB_ID"
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
       CHANGED_FILES=`git diff --name-only $TRAVIS_COMMIT_RANGE | grep ".json"`;
       echo "Changed file = $CHANGED_FILE";
       if  [[ -z $CHANGED_FILES ]] ; then
          echo "Not running CI since no json file was changed." ;
       fi;
    else
       CHANGED_FILES=`git diff --name-only HEAD $(git merge-base HEAD origin/$TRAVIS_BRANCH)| grep ".json"`;
       ./scripts/update_versions.sh $CHANGED_FILES;
    fi;
  
deploy:
  - provider: script
    script: ./scripts/deploy-develop.sh $CHANGED_FILES
    on:
      branch: develop
  - provider: script
    script: ./scripts/deploy-prod.sh $CHANGED_FILES
    on:
      branch: master
  - provider: script
    script: ./scripts/deploy-test.sh $CHANGED_FILES
    on:
      branch: test
  - provider: script
    script: ./scripts/deploy-sandbox.sh $CHANGED_FILES
    on:
      branch: sandbox

