language: generic
sudo: false

env:
  global:
    - DEV_FINAL_TARGET=docs-final
    - DEV_TEST_TARGET=docs-test

notifications:
  email:
    recipients:
      - emanaty@eg.ibm.com
    on_success: always
    on_failure: always

before_install:
    
install:

script:
  - if ./scripts/prepare-target.sh $TRAVIS_COMMIT_RANGE; then echo " $TRAVIS_COMMIT_RANGE is being built"  
  

deploy:
  - provider: script
    script: ./scripts/deploy.sh $DEPLOYMENT_ENV
    on:
      branch: develop
  - provider: script
    script: ./scripts/deploy.sh $DEPLOYMENT_ENV
    on:
      branch: master

after_deploy:
  - ./scripts/update-db.sh
