language: generic

env:
  global:
    - DEV_URL=https://platform-dev.tradelens.com
    - DEV_TL_VERSION=0

notifications:
  email:
    recipients:
      - emanaty@eg.ibm.com
    on_success: always
    on_failure: always

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

script:
  - echo "TRAVIS_PULL_REQUEST = $TRAVIS_PULL_REQUEST"
  - echo "TRAVIS_PULL_REQUEST_BRANCH = $TRAVIS_PULL_REQUEST_BRANCH"
  - echo "TRAVIS_BRANCH = $TRAVIS_BRANCH"
  - echo "TRAVIS_JOB_NAME = $TRAVIS_JOB_NAME"
  - echo "TRAVIS_JOB_ID = $TRAVIS_JOB_ID"
  - echo "TRAVIS_COMMIT_MESSAGE = $TRAVIS_COMMIT_MESSAGE"
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
       CHANGED_FILES=`git diff --name-only $TRAVIS_COMMIT_RANGE | grep ".json"`;
       echo "Changed file = $CHANGED_FILES";
       if  [[ -z $CHANGED_FILES ]] ; then
          echo "Not running CI since no json file was changed." ;
       elif [[ "$TRAVIS_BRANCH" == "develop" ]]; then 
          ./scripts/deploy-develop.sh $CHANGED_FILES;
          export TL_VERSION_DEV=$?
          echo "Out TL_VERSION_DEV = $TL_VERSION_DEV";
          if (( $TL_VERSION_DEV > 0)) ; then
            ./scripts/update_versions.sh $CHANGED_FILES $TL_VERSION_DEV;
          fi;
       fi;
    fi;
