language: generic
sudo: false

env:
  global:
    - DEV_FINAL_TARGET=docs-final/
    - DEV_TEST_TARGET=docs-test/

notifications:
  email:
    recipients:
      - emanaty@eg.ibm.com
    on_success: always
    on_failure: always

script:
  - ./scripts/prepare-target.sh $TRAVIS_COMMIT_RANGE
  
deploy:
  - provider: script
    script: ./scripts/deploy.sh develop $CHANGED_FOLDER $CHANGED_DOC
    on:
      branch: develop
  - provider: script
    script: ./scripts/deploy.sh master $CHANGED_FOLDER $CHANGED_DOC
    on:
      branch: master
  - provider: script
    script: ./scripts/deploy.sh test $CHANGED_FOLDER $CHANGED_DOC 
    on:
      branch: test
  - provider: script
    script: ./scripts/deploy.sh sandbox $CHANGED_FOLDER $CHANGED_DOC 
    on:
      branch: sandbox

after_deploy:
  - ./scripts/update-db.sh 
