language: generic
sudo: false

env:
  global:
    - DEV_FINAL_TARGET=Document-Schema-Deployment/docs-final
    - DEV_TEST_TARGET=Document-Schema-Deployment/docs-test

notifications:
  email:
    recipients:
      - emanaty@eg.ibm.com
    on_success: always
    on_failure: always

before_install:
    
install:

script:
  - if ./scripts/prepare-target.sh $TRAVIS_COMMIT_RANGE $DEV_TEST_TARGET ; then echo "$DEV_TEST_TARGET is being built"; fi
  - if ./scripts/prepare-target.sh $TRAVIS_COMMIT_RANGE $DEV_FINAL_TARGET ; then echo "$DEV_FINAL_TARGET is being built"; fi  
  

deploy:
  - provider: script
    script: ./scripts/deploy.sh $DEPLOYMENT_ENV
    on:
      branch: develop
  - provider: script
    script: ./scripts/deploy.sh $DEPLOYMENT_ENV
    on:
      branch: master

after_deploy:
  - ./scripts/update-db.sh
