language: generic

env:
  global:
    - DEV_URL=https://platform-dev.tradelens.com/
    
notifications:
  email:
    recipients:
      - emanaty@eg.ibm.com
    on_success: always
    on_failure: always

script:
  - CHANGED_FILE=`git diff --name-only $TRAVIS_COMMIT_RANGE | grep ".json"`
  - echo "Changed file = $CHANGED_FILE"
  - if  [[ -z $CHANGED_FILE ]] ; then
     echo "Not running CI since no json file was changed." ;
       exit;
    else
       ./scripts/prepare-target.sh $TRAVIS_COMMIT_RANGE $CHANGED_FILE;
       ./scripts/deploy-develop.sh $CHANGED_FILE 
    fi;
  
deploy:
  - provider: script
    script: ./scripts/deploy-develop.sh $CHANGED_FILE
    on:
      branch: develop
  - provider: script
    script: ./scripts/deploy-prod.sh $CHANGED_FILE
    on:
      branch: master
  - provider: script
    script: ./scripts/deploy-test.sh $CHANGED_FILE
    on:
      branch: test
  - provider: script
    script: ./scripts/deploy-sandbox.sh $CHANGED_FILE
    on:
      branch: sandbox

